ATTRIBUTE_CATEGORY = {
  "color": [
    "white",
    "yellow",
    "maroon",
    "navy",
    "purple",
    "light brown",
    "green",
    "pink",
    "blue",
    "light blue",
    "red",
    "dark",
    "dark colored",
    "brunette",
    "dark brown",
    "transparent",
    "bronze",
    "gold",
    "beige",
    "gray",
    "brown",
    "opaque",
    "copper",
    "dark blue",
    "orange",
    "neon",
    "cream colored",
    "rainbow colored",
    "silver",
    "blond",
    "khaki",
    "black",
    "tan",
    "translucent",
    "light colored",
    "golden",
    "dark green",
    "navy blue",
    "light gray",
    "bright blue",
    "golden brown",
    "light green",
    "bright yellow",
    "dark gray",
    "bright white",
    "dark red",
    "dark purple"
  ],
  "other": [
    "sweet",
    "clear",
    "wii",
    "tinted",
    "analog",
    "powerful",
    "made",
    "scarce",
    "electric",
    "christmas",
    "public",
    "urban",
    "roman",
    "abundant",
    "commercial",
    "deciduous",
    "bright",
    "toy",
    "cordless",
    "real",
    "mixed",
    "evergreen",
    "portable",
    "fluorescent",
    "strong",
    "regular",
    "digital",
    "exterior",
    "oriental",
    "abstract",
    "adidas",
    "chinese",
    "wireless",
    "asian",
    "tropical",
    "wired",
    "rustic",
    "professional",
    "military",
    "simple",
    "safety",
    "disposable",
    "calico",
    "birthday",
    "directional",
    "fancy",
    "nike",
    "sharp",
    "industrial",
    "american",
    "capital",
    "garbage",
    "assorted",
    "electronic",
    "tasty",
    "artificial",
    "caucasian",
    "protective",
    "foreign",
    "double decker",
    "french",
    "fake",
    "formal",
    "designed",
    "tabby",
    "delicious",
    "polar",
    "typical",
    "wrist",
    "wild",
    "sparse",
    "wedding",
    "ugly",
    "winter",
    "polo",
    "sturdy",
    "traffic",
    "burning",
    "lined",
    "intricate",
    "dangling",
    "breaking",
    "paved",
    "loose",
    "high",
    "beautiful",
    "outdoor",
    "crouched",
    "mature",
    "checkered",
    "gloomy",
    "attached",
    "pastel",
    "slanted",
    "fine",
    "weathered",
    "healthy",
    "cracked",
    "heavy",
    "athletic",
    "rocky",
    "floating",
    "plain",
    "halved",
    "pointing",
    "outstretched",
    "still",
    "old fashioned",
    "shallow",
    "cut",
    "chocolate",
    "young",
    "eaten",
    "ivory",
    "discolored",
    "light",
    "decorative",
    "dense",
    "low",
    "teal",
    "spread",
    "perched",
    "immature",
    "textured",
    "outdoors",
    "collared",
    "shaped",
    "inflatable",
    "elevated",
    "narrow",
    "reflected",
    "vanilla",
    "parked",
    "indoors",
    "sheer",
    "rippling",
    "pale",
    "hard",
    "antique",
    "warm",
    "dull",
    "pretty",
    "comfortable",
    "wooded",
    "funny",
    "colorful",
    "handmade",
    "groomed",
    "displayed",
    "corded",
    "straight",
    "uneven",
    "tilted",
    "complete",
    "modern",
    "vibrant",
    "homemade",
    "vintage",
    "rippled",
    "balding",
    "adult",
    "forested",
    "deep",
    "tangled",
    "wavy",
    "elderly",
    "sandy",
    "manicured",
    "ornamental",
    "black framed",
    "insulated",
    "cold",
    "army",
    "bearded",
    "short haired",
    "canned",
    "recycling",
    "married",
    "dental",
    "shooting",
    "doubledecker",
    "musical",
    "mexican",
    "chain link",
    "slate",
    "medieval",
    "maple",
    "recreational",
    "solar",
    "lit up",
    "mountainous",
    "working",
    "casted",
    "organized",
    "stopped",
    "crocheted",
    "well done",
    "trash",
    "surgical",
    "equestrian",
    "dark haired",
    "aerial",
    "crushed",
    "reflecting",
    "bridal",
    "extended",
    "blond haired",
    "organic",
    "special",
    "alone",
    "posted",
    "cute",
    "flavorful",
    "string",
    "festive",
    "cartoon",
    "hilly",
    "tail",
    "projected",
    "underground",
    "motorized",
    "hugging",
    "boxed",
    "moss covered",
    "kicked up",
    "topped",
    "yummy",
    "turned on",
    "autumn",
    "frosting",
    "cubed",
    "dropping",
    "ornately carved",
    "arid",
    "acoustic",
    "medical",
    "flowery",
    "stainless",
    "squeezed",
    "close up",
    "royal",
    "baby",
    "grand",
    "tattooed",
    "launching",
    "veggie",
    "far away",
    "cardboard",
    "bottled",
    "numbered",
    "open air",
    "charging",
    "summer",
    "laundry",
    "circular",
    "cutting",
    "hot",
    "residential",
    "interior",
    "covering",
    "crunchy",
    "roast",
    "tidy",
    "national",
    "ethnic",
    "natural",
    "brown haired",
    "appetizing",
    "black eye",
    "stamped",
    "almost empty",
    "tree covered",
    "cast iron",
    "alcoholic",
    "tree lined",
    "mobile",
    "jean",
    "frothy",
    "breaded",
    "ice covered",
    "indian",
    "flooded",
    "handwritten",
    "turkey",
    "emergency",
    "chocolate covered",
    "artistic",
    "distant",
    "newborn",
    "historical",
    "snow covered",
    "lavender",
    "cheesy",
    "well manicured",
    "english",
    "stringed",
    "vegetarian",
    "religious",
    "barred",
    "engraved",
    "washed up",
    "well seasoned",
    "lovely",
    "hard cover",
    "sand",
    "elegant",
    "half",
    "bloody",
    "halloween",
    "long haired",
    "tagged",
    "coiled",
    "suburban",
    "dining",
    "protesting",
    "seated",
    "wrought iron",
    "grizzly",
    "gathering",
    "hooded",
    "black handled",
    "sugared",
    "chocolate iced",
    "sticky",
    "electrical",
    "comic",
    "mosaic",
    "dead",
    "blue striped",
    "feeding",
    "photography",
    "snow capped",
    "sour",
    "handheld",
    "olympic",
    "old",
    "torn up",
    "fast",
    "watery",
    "topping",
    "multicolored",
    "toothy",
    "listed",
    "mechanical",
    "paisley",
    "ancient",
    "dairy",
    "black haired",
    "knitted",
    "casual",
    "carving",
    "traditional",
    "cropped",
    "free",
    "gated",
    "rural",
    "partially eaten",
    "holed",
    "huddling",
    "flavored",
    "close",
    "half eaten",
    "hearty",
    "cut in half",
    "dirt covered",
    "dust",
    "nighttime",
    "locking",
    "loading"
  ],
  "size": [
    "short",
    "long",
    "wide",
    "thin",
    "tall",
    "thick",
    "huge",
    "miniature",
    "tiny",
    "giant",
    "little",
    "massive",
    "oversized",
    "large",
    "small",
    "skinny",
    "chubby",
    "vast",
    "fat",
    "big"
  ],
  "activity": [
    "walking",
    "sliding",
    "having meeting",
    "posing",
    "skiing",
    "sitting",
    "squatting",
    "hitting",
    "blowing",
    "drinking",
    "waving",
    "looking up",
    "blooming",
    "driving",
    "crashing",
    "staring",
    "laughing",
    "standing",
    "cooking",
    "riding",
    "skating",
    "performing trick",
    "snowboarding",
    "kneeling",
    "crouching",
    "talking",
    "batting",
    "smiling",
    "looking down",
    "bending",
    "hanging",
    "playing",
    "skateboarding",
    "running",
    "flying",
    "eating",
    "grazing",
    "waiting",
    "jumping",
    "splashing",
    "spinning",
    "resting",
    "swinging",
    "reading",
    "spraying",
    "surfing",
    "sleeping",
    "lying",
    "swimming",
    "shopping",
    "rising",
    "singing",
    "fishing",
    "shipping",
    "writing",
    "paddling",
    "bowling",
    "traveling",
    "leaning",
    "catching",
    "sculpting",
    "spitting",
    "marching",
    "pitching",
    "speaking",
    "signing",
    "sewing",
    "kissing",
    "rowing",
    "racing",
    "feasting",
    "soaring",
    "boxing",
    "hiking",
    "filming",
    "cleaning",
    "performing",
    "helping",
    "sporting",
    "greeting",
    "flowing",
    "parachuting",
    "meeting",
    "celebrating",
    "baking",
    "diving",
    "landing",
    "leaping",
    "growing",
    "cheering",
    "serving",
    "shaving",
    "throwing",
    "watching",
    "selling",
    "falling",
    "operating",
    "dancing",
    "smoking",
    "drawing",
    "crossing",
    "climbing",
    "washing",
    "painting",
    "frying",
    "moving"
  ],
  "state": [
    "used",
    "new",
    "oldsliced",
    "lighted",
    "toasted",
    "ripe",
    "fried",
    "shaved",
    "abandoned",
    "trimmed",
    "fenced",
    "painted",
    "dried",
    "juicy",
    "diced",
    "barefoot",
    "bunched",
    "drawn",
    "suspended",
    "seasoned",
    "shirtless",
    "rolled",
    "potted",
    "uncomfortable",
    "overcast",
    "grated",
    "stained",
    "chopped",
    "messy",
    "crowded",
    "raised",
    "vacant",
    "crossed",
    "cushioned",
    "faded",
    "decorated",
    "shadowed",
    "piled",
    "powdered",
    "padded",
    "shredded",
    "wrapped",
    "sealed",
    "mowed",
    "barren",
    "clean",
    "turned",
    "overgrown",
    "framed",
    "breakable",
    "chipped",
    "damaged",
    "crumbled",
    "hazy",
    "edged",
    "sunny",
    "partly cloudy",
    "cloudy",
    "gloved",
    "clumped",
    "patched",
    "dirty",
    "full",
    "inflated",
    "snowy",
    "short sleeved",
    "packed",
    "sunlit",
    "uncooked",
    "roasted",
    "rotten",
    "glazed",
    "scattered",
    "bald",
    "grouped",
    "torn",
    "glowing",
    "unoccupied",
    "hollow",
    "scrambled",
    "illuminated",
    "rimmed",
    "tied",
    "leafless",
    "peeled",
    "sculpted",
    "fallen",
    "upholstered",
    "fresh",
    "unpeeled",
    "half full",
    "packaged",
    "open",
    "melting",
    "closed",
    "unripe",
    "covered",
    "mounted",
    "worn",
    "sprinkled",
    "foggy",
    "sleeveless",
    "unlit",
    "cluttered",
    "carved",
    "grilled",
    "frozen",
    "baked",
    "iced",
    "incomplete",
    "steamed",
    "blurry",
    "boiled",
    "stormy",
    "lit",
    "shut",
    "written",
    "unhealthy",
    "blank",
    "neat",
    "bare",
    "connected",
    "folding",
    "wet",
    "shaded",
    "peeling",
    "folded",
    "muscular",
    "filled",
    "stuffed",
    "tight",
    "empty",
    "shining",
    "long sleeved",
    "stacked",
    "browned",
    "cloudless",
    "printed",
    "busy",
    "misty",
    "rainy",
    "murky",
    "raw",
    "burnt",
    "recessed",
    "choppy",
    "melted",
    "cooked",
    "broken",
    "docked",
    "mashed",
    "planted",
    "whipped",
    "zippered",
    "sliced",
    "enclosed"
  ],
  "material": [
    "rock",
    "paper",
    "wood",
    "metal",
    "hardwood",
    "tin",
    "aluminum",
    "cotton",
    "asphalt",
    "styrofoam",
    "silk",
    "granite",
    "wicker",
    "steel",
    "crystal",
    "vinyl",
    "concrete",
    "leather",
    "porcelain",
    "plastic",
    "diamond",
    "rubber",
    "iron",
    "glass",
    "cobblestone",
    "wool",
    "jeans",
    "gravel",
    "cloth",
    "stainless steel",
    "denim",
    "brick",
    "lace",
    "brass",
    "ceramic",
    "clay",
    "chrome",
    "marble",
    "stone",
    "metallic",
    "wooden",
    "cement",
    "terracotta",
    "dark wood",
    "silver metal",
    "fabric"
  ],
  "texture": [
    "plaid",
    "frosted",
    "crumpled",
    "braided",
    "quilted",
    "wrinkled",
    "paneled",
    "knotted",
    "crispy",
    "crusty",
    "beaded",
    "muddy",
    "barbed",
    "foamy",
    "reflective",
    "unpaved",
    "bushy",
    "creamy",
    "ruffled",
    "furry",
    "carpeted",
    "flowered",
    "polished",
    "jagged",
    "coarse",
    "fuzzy",
    "dusty",
    "soft",
    "puffy",
    "dry",
    "wrinkly",
    "glossy",
    "wispy",
    "tiled",
    "shaggy",
    "greasy",
    "patchy",
    "hairy",
    "fluffy",
    "plush",
    "woven",
    "floral",
    "shiny",
    "shingled",
    "rugged",
    "ridged",
    "rusty",
    "dotted",
    "spiky",
    "patterned",
    "speckled",
    "grassy",
    "feathered",
    "smooth",
    "crisp",
    "floppy",
    "ornate",
    "knit",
    "leafy",
    "rough",
    "striped",
    "floral patterned",
    "graffitied",
    "spotted"
  ],
  "mood": [
    "sad",
    "angry",
    "sleepy",
    "happy",
    "unhappy",
    "curious",
    "calm",
    "enjoying"
  ],
  "shape": [
    "curly",
    "crooked",
    "triangular",
    "pointy",
    "elongated",
    "oblong",
    "octagonal",
    "sloped",
    "curved",
    "round",
    "domed",
    "rounded",
    "bent",
    "curled",
    "winding",
    "angled",
    "spiral",
    "rectangular",
    "twisted",
    "irregular",
    "steep",
    "square",
    "flat",
    "cylindrical",
    "arched",
    "curvy",
    "heart shaped",
    "bucking",
    "arch shaped"
  ],
  "orientation": [
    "horizontal",
    "down",
    "upside down",
    "overhead",
    "upper",
    "vertical",
    "up",
    "lower"
  ],
  "gender": [
    "female",
    "male"
  ]
}


ATTRIBUTE_LIST = list(set([att for att_list in ATTRIBUTE_CATEGORY.values() for att in att_list]))